const data = {
    products: [{
            _id: '1',
            name: 'Nike slim Shirt',
            catedory: 'Shirts',
            image: '/image/p1.jpg',
            price: 120,
            countInStock: 20,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Adidas Shirt',
            catedory: 'Shirts',
            image: '/image/p2.jpg',
            price: 110,
            countInStock: 10,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 7,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Lacoste Shirt',
            catedory: 'Shirts',
            image: '/image/p3.jpg',
            price: 154,
            countInStock: 11,
            brand: 'Lacoste',
            rating: 4.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Nike slim Pant',
            catedory: 'Pants',
            image: '/image/p4.jpg',
            price: 160,
            countInStock: 0,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Puma slim Pant',
            catedory: 'Pant',
            image: '/image/p5.jpg',
            price: 130,
            countInStock: 13,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 20,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Adidas fit Pant',
            catedory: 'Pant',
            image: '/image/p6.jpg',
            price: 130,
            countInStock: 25,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 12,
            description: 'high quality product',
        },
    ],
};
export default data;